name: Docker Build
on:
    push:
env:
    DOCKER_REGISTRY_IMAGE: ghcr.io/fortrabbit/craft-copy

jobs:
    build:
        name: Build
        runs-on: ubuntu-18.04
        defaults:
            run:
                working-directory: ./docker
        strategy:
            fail-fast: false
            matrix:
                craft_image_tag: ['7.2', '7.3', '7.4', '8.0']
        steps:
            -   uses: actions/checkout@v1

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Slugify branch/tag name
                shell: bash
                run: echo "##[set-output name=slug;]$(echo $GITHUB_REF | sed -E 's/refs\/(heads|tags)\///g' | iconv -t ascii//TRANSLIT | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)"
                id: branch_slug
                # Usage: ${{ steps.branch_slug.outputs.slug }}

            -   name: Build docker image
                working-directory: ./docker
                run: |
                    docker build --build-arg CRAFT_IMAGE_TAG="${{ matrix.craft_image_tag }}" \
                        --tag $DOCKER_REGISTRY_IMAGE:${{ matrix.craft_image_tag }} \
                        --tag $DOCKER_REGISTRY_IMAGE:${{ matrix.craft_image_tag }}_${{ steps.branch_slug.outputs.slug }} .

            -   name: Push development image to registry
                run: |
                    docker push $DOCKER_REGISTRY_IMAGE:${{ matrix.craft_image_tag }}_${{ steps.branch_slug.outputs.slug }}

            # Only publish main image (:8.0) on tag push matching "v1.0.5" format
            # https://stackoverflow.com/questions/58862864/github-actions-ci-conditional-regex
            -   name: Check Tag
                id: check-tag
                run: |
                    if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                      echo ::set-output name=match::true
                    fi
            -   name: Publish main image
                if: steps.check-tag.outputs.match == 'true'
                run: |
                    docker tag
                    docker push $DOCKER_REGISTRY_IMAGE:${{ matrix.craft_image_tag }}
